version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "portal-api-serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7ui7g4dpofol"
s3_prefix = "portal-api-serverless"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
